In [4]:
import numpy as np
a = np.arange(0, 10) #one-dimensional array
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
c = a.reshape(2,5) #creates a new, 2-d array from the declared existing array
#2 = num of rows; 5 = num of cols
c

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [9]:
b = np.array([np.arange(4), np.arange(4)])
#desired amt of rows contains in [] and separated by commas
#this one has two bracket groups = 2 rows
#columns explicitly declared
b

array([[0, 1, 2, 3],
       [0, 1, 2, 3]])

In [11]:
np.arange(5) #another way to create a 1D array
#num of cols explicitly declared; will auto pop. (0,5), exclusive

array([0, 1, 2, 3, 4])

In [15]:
a.shape
#show shape of a 1D array
#returns num of elements based on dimension, from 0; (x,) = one row

(10,)

In [16]:
np.arange(3,) #third way to create a 1D array

array([0, 1, 2])

In [17]:
b.shape
#returns shape of array in mxn format 

(2, 4)

In [21]:
d = list(range(5,10))
d #creates iterator list btwn range of given ints

[5, 6, 7, 8, 9]

In [22]:
listA = list(range(0,10))
listB = list(range(10,20))
listA + listB #concatenates both lists

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [25]:
#can sort arrays by condition
np.where(a>5) #np.where(condition containing name)

(array([6, 7, 8, 9], dtype=int64),)

In [26]:
np.nonzero(a)

(array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int64),)

In [27]:
dd = np.array([np.arange(0,5), np.arange(0,5)])
dd #np.array([np.arange(num range), np.arange(second range)]) -> one block, two rows defined

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [36]:
#how to declare a 3D array
e = np.array(np.arange(0,20)).reshape(2,2,5) #creates an array from an existing 2D array
e #num of blocks, rows and cols made evenly w/ given array

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]])

In [47]:
f = np.array([np.arange(4), np.arange(4), np.arange(4)])
f #2d array

array([[0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3]])

In [37]:
a[3] #accessing element w/ 1D array

3

In [41]:
b[1,2] #access element w/ 2D array
#row num, index num

2

In [42]:
b[::, 2:4:] #all rows, btwn intvl of columns
#also slicing?

array([[2, 3],
       [2, 3]])

In [49]:
e[1,1,3]
#access element w/ 3D array
#name[block num, row num, col num]

18

In [50]:
e[::,::] #two colons = all

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]])

In [52]:
a[5:8] #slicing a 1D array; will return elements in this range
#array a is now what is below

array([5, 6, 7])

In [54]:
c_slice = a.copy()[5:6] #can also make a copy of the original and assign the slice as a new array
c_slice

array([5])

In [55]:
e[0:2, 1, 2] #slicing 3D array

array([ 7, 17])

In [60]:
f_copy = f.copy()[1:5, 3]
f_copy

array([3, 3])

In [61]:
e[0] = 4
e #reassignment; why is e still its original form after slicing

array([[[ 4,  4,  4,  4,  4],
        [ 4,  4,  4,  4,  4]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]])

In [62]:
e[1, 0, 3] = 20
e #reassignment of a specific number in 3D array

array([[[ 4,  4,  4,  4,  4],
        [ 4,  4,  4,  4,  4]],

       [[10, 11, 12, 20, 14],
        [15, 16, 17, 18, 19]]])