**1. Create 4*4 2-Dimensional array with random numbers. Name the array ‘arr1’. (10 points)**

In [2]:
import numpy as np
arr1 = np.random.randn(4, 4)
arr1

ImportError: cannot import name 'lib' from partially initialized module 'numpy' (most likely due to a circular import) (C:\Users\csuser\AppData\Roaming\Python\Python310\site-packages\numpy\__init__.py)

**2. Select the number in the third row, third column from arr1.  (10 points)**

In [1]:
a = arr1[2, 2]
a

NameError: name 'arr1' is not defined

**3. Create a new array, arr_slice, which shall be built from arr1 with only the odd rows.  (10 points)**

In [5]:
arr_slice = np.delete(arr1, [0,2], axis=0)
arr_slice

array([[ 0.99082384,  0.08834509,  0.02868087, -0.49226251],
       [ 1.55015797, -0.24520872,  1.32617451,  0.59929369]])

**4. Assign the value 12345  to the last number in arr_slice. Did it change the values in arr1?  (10 points)**

In [6]:
arr_slice[0,1] = 12345
arr_slice #not sure why elements were multiplied below

array([[ 9.90823843e-01,  8.83450866e-02,  2.86808748e-02,
        -4.92262505e-01],
       [ 1.55015797e+00, -2.45208719e-01,  1.32617451e+00,
         1.23450000e+04]])

In [7]:
arr1

array([[ 0.27732852,  0.30347521, -1.13752566, -1.18251592],
       [ 0.99082384,  0.08834509,  0.02868087, -0.49226251],
       [ 1.73324367, -0.85525374, -0.16295913, -0.90462991],
       [ 1.55015797, -0.24520872,  1.32617451,  0.59929369]])

The values in arr1 did not change due to reassignment in arr_slice.

**5. Transpose arr1.  (10 points)**

In [64]:
arr1.transpose()

array([[ 0.27732852,  0.99082384,  1.73324367,  1.55015797],
       [ 0.30347521,  0.08834509, -0.85525374, -0.24520872],
       [-1.13752566,  0.02868087, -0.16295913,  1.32617451],
       [-1.18251592, -0.49226251, -0.90462991,  0.59929369]])

**6. Create another array 5 * 5 2-Dimensional array with numbers from 0 to 50 with only odd numbers. Name this array ‘arr2’.  (10 points)**

In [60]:
arr2 = np.arange(0,50)
arr2=arr2[(~arr2%2==0)]
arr2=arr2.reshape(5,5)
arr2

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19],
       [21, 23, 25, 27, 29],
       [31, 33, 35, 37, 39],
       [41, 43, 45, 47, 49]])

**7. Stack arr1 and arr2 horizontally. Name it arr_new. If it reports an error, find the problem and re-define arr2 to make it work.  (10 points)**

In [61]:
arr2=np.delete(arr2, 0, axis=0)
arr_new = np.hstack((arr1, arr2)) #all the input arrays must have same number of dimensions
arr_new #solution is in scientific notation

array([[ 2.77328524e-01,  3.03475208e-01, -1.13752566e+00,
        -1.18251592e+00,  1.10000000e+01,  1.30000000e+01,
         1.50000000e+01,  1.70000000e+01,  1.90000000e+01],
       [ 9.90823843e-01,  8.83450866e-02,  2.86808748e-02,
        -4.92262505e-01,  2.10000000e+01,  2.30000000e+01,
         2.50000000e+01,  2.70000000e+01,  2.90000000e+01],
       [ 1.73324367e+00, -8.55253740e-01, -1.62959126e-01,
        -9.04629909e-01,  3.10000000e+01,  3.30000000e+01,
         3.50000000e+01,  3.70000000e+01,  3.90000000e+01],
       [ 1.55015797e+00, -2.45208719e-01,  1.32617451e+00,
         5.99293695e-01,  4.10000000e+01,  4.30000000e+01,
         4.50000000e+01,  4.70000000e+01,  4.90000000e+01]])

**8. Split arr_new vertically into two arrays.  (10 points)**

In [62]:
np.vsplit(arr_new, 2)

[array([[ 2.77328524e-01,  3.03475208e-01, -1.13752566e+00,
         -1.18251592e+00,  1.10000000e+01,  1.30000000e+01,
          1.50000000e+01,  1.70000000e+01,  1.90000000e+01],
        [ 9.90823843e-01,  8.83450866e-02,  2.86808748e-02,
         -4.92262505e-01,  2.10000000e+01,  2.30000000e+01,
          2.50000000e+01,  2.70000000e+01,  2.90000000e+01]]),
 array([[ 1.73324367, -0.85525374, -0.16295913, -0.90462991, 31.        ,
         33.        , 35.        , 37.        , 39.        ],
        [ 1.55015797, -0.24520872,  1.32617451,  0.59929369, 41.        ,
         43.        , 45.        , 47.        , 49.        ]])]

**9. Sort arr1 by each row in descending order.  (10 points)**

In [67]:
arr1.sort(1)
arr1[::-1]

array([[-0.24520872,  0.59929369,  1.32617451,  1.55015797],
       [-0.90462991, -0.85525374, -0.16295913,  1.73324367],
       [-0.49226251,  0.02868087,  0.08834509,  0.99082384],
       [-1.18251592, -1.13752566,  0.27732852,  0.30347521]])

**10.  Create an 1D array, a 2D array, and a 3D array as shown in the picture below. (10 points)**

In [78]:
#1D Array
a = np.arange(0,4)
np.delete(a, [0])

array([1, 2, 3])

In [79]:
#2D Array
b = np.arange(0,9).reshape(3,3)
b[0:3, 0] = 1
b[0:3, 1] = 2
b[0:3, 2] = 3
b

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [83]:
#3D Array
c = np.arange(27).reshape(3,3,3)
c[0:3, 0:3, 0] = 1
c[0:3, 0:3, 1] = 2
c[0:3, 0:3, 2] = 3
c

array([[[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]],

       [[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]],

       [[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]]])

THIS IS AN INDIVIDUAL ASSIGNMENT. YOU MAY NOT DISCUSS THIS ASSIGNMENT WITH ANYONE WITHIN OR OUTSIDE THE CLASS (except the instructor).
- DO not discuss your approaches or your code with colleagues. There are many ways to implement this assignment, and it is extremely easy to spot code that has been inspired by someone else’s code and to identify unauthorized collaborations.
- If you choose to utilize something you find online, cite that resource, but DO NOT share that resource with anyone else.
By submitting this assignment, you certify that no unauthorized assistance has been received or given in the completion of this work.

- McKenzie Church